baseURL = 'http://localhost/'
languageCode = 'en-us'
title = "ikstream's notes"
theme = 'archie'
copyright = ""

[params]
mode="auto"
subtitle = "My notes on IT-Security and tech"
#mathjax = true # enable MathJax support
#katex = true # enable KaTeX support

[pagination]
pagerSize = 20

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/ikstream"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3
